demuxing_decoding:demuxing_decoding.c
        gcc  demuxing_decoding.c  -o demuxing_decoding -g -I ./ffmpeg-5.0.1/include -L ./ffmpeg-5.0.1/lib/ -l avcodec -l avutil -l avformat -l swresample  -lm -Wl,-rpath=./ffmpeg-5.0.1/lib/
                                        
